# The native Vagrant docker isn't great at handling docker-compose files with existing
#   images, hence installing this plugin.
unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  system("vagrant up")
  exit
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true #debugging
  end
  # Handle port forwarding
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Provision runtime
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
end